# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/natha/Documents/MS_CS/8700/sd_assignment2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/natha/Documents/MS_CS/8700/sd_assignment2

#=============================================================================
# Targets provided globally by CMake.


# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast


# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast


# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named A2

# Build rule for target.
A2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 A2
.PHONY : A2

# fast build rule for target.
A2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/A2.dir/build.make CMakeFiles/A2.dir/build
.PHONY : A2/fast

Zoo.o: Zoo.cpp.o
.PHONY : Zoo.o

# target to build an object file
Zoo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/A2.dir/build.make CMakeFiles/A2.dir/Zoo.cpp.o
.PHONY : Zoo.cpp.o

Zoo.i: Zoo.cpp.i
.PHONY : Zoo.i

# target to preprocess a source file
Zoo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/A2.dir/build.make CMakeFiles/A2.dir/Zoo.cpp.i
.PHONY : Zoo.cpp.i

Zoo.s: Zoo.cpp.s
.PHONY : Zoo.s

# target to generate assembly for a file
Zoo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/A2.dir/build.make CMakeFiles/A2.dir/Zoo.cpp.s
.PHONY : Zoo.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/A2.dir/build.make CMakeFiles/A2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/A2.dir/build.make CMakeFiles/A2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/A2.dir/build.make CMakeFiles/A2.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... A2"
	@echo "... Zoo.o"
	@echo "... Zoo.i"
	@echo "... Zoo.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

